/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appAddsNumbers() {
        App classUnderTest = new App();
        assertEquals(5, classUnderTest.addNumbers(2, 3), "Result of 2+3 should be 5");
    }

    private static Stream<Arguments> provideArgumentsForSum() {
        return Stream.of(
          Arguments.of(5, 5, 10)
        );
    }

    @ParameterizedTest
    @MethodSource("provideArgumentsForSum")
    void appAddsNumbersToTen(Integer a, Integer b, Integer sum) {
        App classUnderTest = new App();
        assertEquals(sum, classUnderTest.addNumbers(a, b), "Result of a+b should be equal to sum");
    }
}
